### ISSUE TITLE
Lock type not working

### ISSUE THREAD

**Issue by ratsoid** [bwp91/homebridge-ewelink#204]
I use a sonoff as a Lock accessory simulation, but not it's not working anymore. It does work as a regular switch.

I have cleared all the cache, latest hb 1.3.1, latest node, homebridge image, pi3

**Comment by bwp91** [comment]
Hi, please see if v5.0.2 fixes this? Thanks

**Comment by ratsoid** [comment]
> 
> 
> Hi, please see if v5.0.2 fixes this? Thanks

no luck :(

**Comment by bwp91** [comment]
Are there any messages/errors in the logs when you restart Homebridge or control the device?

**Comment by ratsoid** [comment]
No errors, just the regular:

[24/02/2021, 13:38:29] [eWeLink] [Door Sonoff] initialised and LAN mode unavailable as unreachable.
[24/02/2021, 13:38:29] [eWeLink] ✓ Setup complete. Thanks for using this plugin, I hope you find it helpful!

Can't figure out why my sonoff doesn't work on LAN though... 

wrong: _I might be doozy from all the logs, but when I set it up as a Lock, I don't get this:
[24/02/2021, 13:36:11] [eWeLink] [Door Sonoff] has been added to Homebridge._

**Comment by bwp91** [comment]
Is the accessory in the Home app appearing as a switch **and** a lock? I've just tested this simulation myself and noticed this. I have released an update v5.0.3 to remove the switch service so it just appears as a lock.

Does this update improve things for you?

**Comment by ratsoid** [comment]
well i had them appearing as a switch and a lock at the same time, I thought it had something to do with cache, cleared that and restarted homebridge and hasn't happened since.

5.0.3 unfortunately still doesn't fix the issue.

FYI, when I push the button on the Sonoff, Homekit does see that and it notifies me (Lock's do that in homekit)

**Comment by bwp91** [comment]
Could you post your ewelink config? Just the `groups` section, and redact a couple of characters from the device ID for good measures!

**Comment by ratsoid** [comment]
`        {
            "name": "eWeLink",
            "countryCode": "+40",
            "username": "",
            "password": "",
            "mode": "auto",
            "groups": [
                {
                    "deviceId": "1000######",
                    "label": "Door",
                    "type": "lock",
                    "operationTime": 90
                }
            ],
            "platform": "eWeLink"
        }`

https://i.imgur.com/ZerShlQ.png

**Comment by bwp91** [comment]
Please select a value in the “Device Setup” field :)

**Comment by ratsoid** [comment]
Yeah that did it BUT i need to mention that at first I had the Device Setup value set to Single Channel and it wasn't working so I'm sure that you managed to fix the initial problem, although the last part my stupid brain

Thank you @bwp91 , you're amazing!

**Comment by bwp91** [comment]
You are correct in that there was a change I needed to make to the code first!

I'm just about to release an update which will print a message to the log if this 'Device Type' field is empty!

Thanks for bringing this to my attention and glad we got it working!
